name: Update CONTRIBUTORS file

on:
  push:
    branches: [ development ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@v3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: '[actions] update contributors'
          github-token: ${{ secrets.GITHUB_TOKEN }}