name: 'Publish'

on:
  release:
    types: [ published ]

jobs:
  setup:
    name: Setup node and environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Download dependencies
        run: yarn

  build:
    name: Build package
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          
      - name: Build package
        run: yarn build

  publish:
    name: Publish package
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Publish
        run: yarn publish --new-version ${{ github.event.release.tag }} --access public

      - name: Update package version
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'package.json'
          commit-msg: '[actions] ${{ github.event.release.tag }} version'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  wrapup:
    name: Publish package
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge to production
        uses: devsmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}